[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
protocol = "82VDeeUheGof2qZ7gM8sTCFLB3xoqFexF7uxet7Cv9N3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 10000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000"
