[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
protocol = "5QBudxMGUXjZ4kQHEa7XvsG8m2bZA19xoPJqwJ7QnW7R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tommy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
